export const productsData = [
  {
    id: 1,
    name: "Wireless Headphones",
    category: "Electronics",
    price: 79.99,
    rating: 4.5,
    icon: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=600&auto=format&fit=crop",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life. Perfect for music lovers.",
    inStock: true,
    specifications: ["Bluetooth 5.0 connectivity", "30-hour battery life", "Active Noise Cancellation"],
  },
  {
    id: 2,
    name: "Smart Watch",
    category: "Wearables",
    price: 199.99,
    rating: 4.8,
    icon: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=600&auto=format&fit=crop",
    description: "Feature-rich smartwatch with advanced health tracking, fitness modes, and mobile notifications.",
    inStock: true,
    specifications: ["Heart rate monitor", "Sleep tracking", "GPS tracking", "Water resistant"],
  },
  {
    id: 3,
    name: "Laptop Backpack",
    category: "Accessories",
    price: 49.99,
    rating: 4.6,
    icon: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=600&auto=format&fit=crop",
    description: "Durable and stylish backpack with dedicated laptop compartment and multiple organization pockets.",
    inStock: true,
    specifications: ["Fits up to 17-inch laptop", "Water-resistant material", "USB charging port"],
  },
  {
    id: 4,
    name: "Phone Stand",
    category: "Accessories",
    price: 19.99,
    rating: 4.3,
    icon: "https://images.unsplash.com/photo-1586105251261-72a756497a11?q=80&w=600&auto=format&fit=crop",
    description: "Adjustable phone stand perfect for desk use during video calls and media consumption.",
    inStock: false,
    specifications: ["Adjustable angle", "Non-slip pads", "Aluminum construction"],
  },
  {
    id: 5,
    name: "USB-C Cable",
    category: "Electronics",
    price: 14.99,
    rating: 4.7,
    icon: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?q=80&w=600&auto=format&fit=crop",
    description: "3-meter long durable USB-C cable with fast charging support and data transfer.",
    inStock: true,
    specifications: ["3 meters long", "Fast charging support", "Braided design"],
  },
  {
    id: 6,
    name: "Portable Charger",
    category: "Electronics",
    price: 34.99,
    rating: 4.9,
    icon: "https://images.unsplash.com/photo-1609592424109-dd9892f1b177?q=80&w=600&auto=format&fit=crop",
    description: "20000mAh portable power bank with dual USB ports and LCD display.",
    inStock: true,
    specifications: ["20000mAh capacity", "Dual USB ports", "LCD display"],
  },
  {
    id: 7,
    name: "Mechanical Keyboard",
    category: "Electronics",
    price: 89.99,
    rating: 4.7,
    icon: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?q=80&w=600&auto=format&fit=crop",
    description: "Tactile and responsive mechanical gaming keyboard with customizable RGB backlighting.",
    inStock: true,
    specifications: ["RGB Backlit", "Blue switches", "Detachable USB-C"],
  },
  {
    id: 8,
    name: "Wireless Gaming Mouse",
    category: "Electronics",
    price: 59.99,
    rating: 4.6,
    icon: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=600&auto=format&fit=crop",
    description: "Ergonomic wireless mouse featuring ultra-fast response time and precise optical sensor.",
    inStock: true,
    specifications: ["16000 DPI sensor", "Rechargeable battery", "6 programmable buttons"],
  },
  {
    id: 9,
    name: "Minimalist Leather Wallet",
    category: "Accessories",
    price: 29.99,
    rating: 4.4,
    icon: "https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=600&auto=format&fit=crop",
    description: "Slim genuine leather wallet with RFID blocking technology and quick card access slot.",
    inStock: true,
    specifications: ["Genuine leather", "RFID blocking", "Holds up to 8 cards"],
  },
  {
    id: 10,
    name: "Stainless Steel Water Bottle",
    category: "Accessories",
    price: 24.99,
    rating: 4.8,
    icon: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?q=80&w=600&auto=format&fit=crop",
    description: "Double-walled vacuum insulated water bottle that keeps your drinks cold for 24 hours.",
    inStock: true,
    specifications: ["Vacuum insulated", "BPA-Free steel", "Leak-proof lid"],
  }
];

export function getProductById(id) {
  return productsData.find(product => product.id === parseInt(id));
}

export function getRelatedProducts(currentId) {
  return productsData.filter(product => product.id !== parseInt(currentId)).slice(0, 3);
}